#Requires -Version 7.0
param(
    [Parameter(Mandatory = $true)]
    [string]$TemplateName,

    [Parameter(Mandatory = $true)]
    [string]$Owner,

    [Parameter(Mandatory = $false)]
    [string]$Runtime = "NODE|20-lts",

    [Parameter(Mandatory = $false)]
    [ValidateSet("bicep", "terraform")]
    [string]$TemplateType = "bicep"
)

$ErrorActionPreference = "Stop"
$templateRoot = Join-Path "catalog" $TemplateName
$manifestPath = Join-Path "catalog/manifests" "$TemplateName.manifest.yaml"

if (Test-Path $templateRoot) {
    Write-Error "Template folder already exists: $templateRoot"
}

New-Item -ItemType Directory -Path $templateRoot -Force | Out-Null

$isTerraform = $TemplateType -eq "terraform"
$runner = if ($isTerraform) { "mcr.microsoft.com/deployment-environments/runners/terraform:latest" } else { "ARM" }
$templatePath = if ($isTerraform) { "main.tf" } else { "main.bicep" }
$environmentParameterId = if ($isTerraform) { "environment_name" } else { "environmentName" }

$environmentYaml = @"
name: $TemplateName
version: 0.1.0
summary: Candidate pattern scaffold generated by agent workflow.
description: Update this scaffold before promoting to approved.
runner: $runner
templatePath: $templatePath

parameters:
  - id: $environmentParameterId
    name: Environment Name
    description: Name for the deployment environment.
    type: string
    default: $TemplateName

  - id: runtime
    name: Runtime
    description: Workload runtime stack.
    type: string
    default: $Runtime
"@

$mainBicep = @"
@description('Environment name for resource naming')
param environmentName string

@description('Runtime stack')
param runtime string = '$Runtime'

@description('Location for resources')
param location string = resourceGroup().location

output summary string = 'Scaffold template $TemplateName ready for extension.'
"@

$mainTf = @"
terraform {
  required_version = ">= 1.5.0"
}

variable "environment_name" {
  type        = string
  description = "Environment name for resource naming"
}

variable "runtime" {
  type        = string
  description = "Runtime stack"
  default     = "$Runtime"
}

output "summary" {
  value = "Scaffold template $TemplateName ready for extension."
}
"@

$readme = @"
---
title: $TemplateName Pattern
description: Candidate scaffold generated for platform review
author: Microsoft
ms.date: 2026-06-03
ms.topic: reference
keywords:
  - scaffold
  - candidate
estimated_reading_time: 2
---

## Purpose

This is a generated scaffold. Extend this pattern with enterprise controls before approval.

## Owner

$Owner

## Next steps

1. Implement required resources.
2. Update manifest validation commands.
3. Run CLI validation.
4. Open PR for platform review.
"@

$templateArtifactType = if ($isTerraform) { "terraform" } else { "bicep" }
$templateArtifactPath = "catalog/$TemplateName/$templatePath"
$validationCommand = if ($isTerraform) {
  "terraform -chdir=catalog/$TemplateName init -backend=false && terraform -chdir=catalog/$TemplateName validate"
} else {
  "az bicep build --file catalog/$TemplateName/main.bicep"
}

$manifest = @"
id: $TemplateName
version: 0.1.0
status: candidate
owners:
  platform: $Owner
description: Candidate pattern scaffold generated by workflow.
source:
  repository: <GITHUB_OR_AZURE_REPOS_REPO_URL>
  path: catalog/$TemplateName
artifacts:
  template:
    type: $templateArtifactType
    path: $templateArtifactPath
  environmentDefinition:
    path: catalog/$TemplateName/environment.yaml
inputs:
  required:
    - $environmentParameterId
  optional:
    - runtime
validation:
  commands:
    - $validationCommand
governance:
  codeownersRequired: true
  requiredApprovers:
    - $Owner
promotion:
  path:
    - candidate
    - approved
  criteria:
    - validation-passed
    - platform-owner-approved
"@

Set-Content -Path (Join-Path $templateRoot "environment.yaml") -Value $environmentYaml
if ($isTerraform) {
  Set-Content -Path (Join-Path $templateRoot "main.tf") -Value $mainTf
} else {
  Set-Content -Path (Join-Path $templateRoot "main.bicep") -Value $mainBicep
}
Set-Content -Path (Join-Path $templateRoot "README.md") -Value $readme
Set-Content -Path $manifestPath -Value $manifest

Write-Output "Scaffold created: $templateRoot"
Write-Output "Manifest created: $manifestPath"
