#!/usr/bin/env bash
set -euo pipefail

TEMPLATE_NAME=""
OWNER=""
RUNTIME="NODE|20-lts"
TEMPLATE_TYPE="bicep"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --template-name)
      TEMPLATE_NAME="$2"
      shift 2
      ;;
    --owner)
      OWNER="$2"
      shift 2
      ;;
    --runtime)
      RUNTIME="$2"
      shift 2
      ;;
    --template-type)
      TEMPLATE_TYPE="$2"
      shift 2
      ;;
    *)
      echo "Unknown option: $1"
      exit 1
      ;;
  esac
done

if [[ -z "$TEMPLATE_NAME" || -z "$OWNER" ]]; then
  echo "Missing --template-name or --owner"
  exit 1
fi

if [[ "$TEMPLATE_TYPE" != "bicep" && "$TEMPLATE_TYPE" != "terraform" ]]; then
  echo "Invalid --template-type. Use bicep or terraform"
  exit 1
fi

template_root="catalog/$TEMPLATE_NAME"
manifest_path="catalog/manifests/$TEMPLATE_NAME.manifest.yaml"

if [[ -d "$template_root" ]]; then
  echo "Template already exists: $template_root"
  exit 1
fi

mkdir -p "$template_root"

if [[ "$TEMPLATE_TYPE" == "terraform" ]]; then
  runner="mcr.microsoft.com/deployment-environments/runners/terraform:latest"
  template_path="main.tf"
  required_input="environment_name"
  template_type_manifest="terraform"
  validation_cmd="terraform -chdir=catalog/$TEMPLATE_NAME init -backend=false && terraform -chdir=catalog/$TEMPLATE_NAME validate"
else
  runner="ARM"
  template_path="main.bicep"
  required_input="environmentName"
  template_type_manifest="bicep"
  validation_cmd="az bicep build --file catalog/$TEMPLATE_NAME/main.bicep"
fi

cat > "$template_root/environment.yaml" <<EOF
name: $TEMPLATE_NAME
version: 0.1.0
summary: Candidate pattern scaffold generated by agent workflow.
description: Update this scaffold before promoting to approved.
runner: $runner
templatePath: $template_path
EOF

if [[ "$TEMPLATE_TYPE" == "terraform" ]]; then
cat > "$template_root/main.tf" <<EOF
terraform {
  required_version = ">= 1.5.0"
}

variable "environment_name" {
  type        = string
  description = "Environment name for resource naming"
}

variable "runtime" {
  type        = string
  description = "Runtime stack"
  default     = "$RUNTIME"
}

output "summary" {
  value = "Scaffold template $TEMPLATE_NAME ready for extension."
}
EOF
else
cat > "$template_root/main.bicep" <<EOF
@description('Environment name for resource naming')
param environmentName string

@description('Runtime stack')
param runtime string = '$RUNTIME'

@description('Location for resources')
param location string = resourceGroup().location

output summary string = 'Scaffold template $TEMPLATE_NAME ready for extension.'
EOF
fi

cat > "$template_root/README.md" <<EOF
---
title: $TEMPLATE_NAME Pattern
description: Candidate scaffold generated for platform review
author: Microsoft
ms.date: 2026-06-03
ms.topic: reference
keywords:
  - scaffold
  - candidate
estimated_reading_time: 2
---

## Purpose

This is a generated scaffold. Extend this pattern with enterprise controls before approval.

## Owner

$OWNER
EOF

cat > "$manifest_path" <<EOF
id: $TEMPLATE_NAME
version: 0.1.0
status: candidate
owners:
  platform: $OWNER
description: Candidate pattern scaffold generated by workflow.
source:
  repository: <GITHUB_OR_AZURE_REPOS_REPO_URL>
  path: catalog/$TEMPLATE_NAME
artifacts:
  template:
    type: $template_type_manifest
    path: catalog/$TEMPLATE_NAME/$template_path
  environmentDefinition:
    path: catalog/$TEMPLATE_NAME/environment.yaml
inputs:
  required:
    - $required_input
validation:
  commands:
    - $validation_cmd
governance:
  codeownersRequired: true
  requiredApprovers:
    - $OWNER
promotion:
  path:
    - candidate
    - approved
  criteria:
    - validation-passed
    - platform-owner-approved
EOF

echo "Scaffold created: $template_root"
echo "Manifest created: $manifest_path"
